import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Nabvar from '../components/navbar'
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Codeswear - Wear the code</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nabvar />
            <Footer />
        </>
    )
}
